name: backend-node

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - 'node-server/**/*'

env:
  EXTEND_ESLINT: true

jobs:
  deps-and-codegen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node_modules
        uses: actions/cache@main
        id: cache-node-server
        env:
          cache-name: cache-node-server
        with:
          path: node-server/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('node-server/yarn.lock') }}

      - name: Install dependencies
        # Always run this, so it throws if the package and lockfile don't match
        run: cd node-server && yarn install --production=false --non-interactive --frozen-lockfile --cache-folder ~/node_modules/.cache/yarn

      - name: GQL Codegen
        run: cd node-server && yarn run gql-codegen

      - uses: actions/upload-artifact@v2-preview
        with:
          name: generated
          path: "./node-server/graphql-types.ts*"

  test:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Download GQL codegen
        uses: actions/download-artifact@v2-preview
        with:
          name: generated
          path: node-server/
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node-server
        with:
          path: node-server/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('node-server/yarn.lock') }}
      - run: cd node-server && yarn jest

  eslint:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node-server
        with:
          path: node-server/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('node-server/yarn.lock') }}
      - name: Download GQL codegen
        uses: actions/download-artifact@v2-preview
        with:
          name: generated
          path: src/
      - run: cd node-server && yarn eslint

  prettier:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node-server
        with:
          path: node-server/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('node-server/yarn.lock') }}
      - run: cd node-server && yarn run prettier:check

  audit:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node-server
        with:
          path: node-server/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('node-server/yarn.lock') }}
      - run: yarn audit --groups dependencies
