name: frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  EXTEND_ESLINT: true

jobs:
  deps-and-codegen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node_modules
        uses: actions/cache@main
        id: cache-node
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        # Always run this, so it throws if the package and lockfile don't match
        run: yarn install --non-interactive --frozen-lockfile --cache-folder ~/node_modules/.cache/yarn

      - uses: actions/upload-artifact@v2-preview
        with:
          name: generated
          path: "./src/**/__generated__/*"

  yarn-build:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn build

      - name: yarn analyze
        run: yarn run analyze
      - uses: actions/upload-artifact@v2-preview
        with:
          name: analyze
          path: ./report.html

  test:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn jest

  eslint:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn eslint

  prettier:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn run prettier:check

  audit:
    runs-on: ubuntu-latest
    needs: deps-and-codegen
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn audit --groups dependencies
